# TransAgent: Transfer Vision-Language Foundation Models with Heterogeneous Agent Collaboration
DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 4
  TEST:
    BATCH_SIZE: 100
  NUM_WORKERS: 8

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

OPTIM:
  NAME: "sgd"
  LR: 0.0025
  MAX_EPOCH: 20
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5

TRAIN:
  PRINT_FREQ: 20

MODEL:
  BACKBONE:
    NAME: "ViT-B/16"

TRAINER:
  TRANSAGENT:
    N_CTX_VISION: 4
    N_CTX_TEXT: 4
    CTX_INIT: "a photo of a"
    PREC: "fp16"
    PROMPT_DEPTH_VISION: 3
    PROMPT_DEPTH_TEXT: 3
    TEXT_LOSS_WEIGHT: 0.0
    IMAGE_LOSS_WEIGHT: 0.0
    LOGITS_LOSS_WEIGHT: 0.0
    MM_LOSS_TYPE: "kl"
    MM_LOSS_WEIGHT: 1.0
    MM_TEMP: 1.0
    LLM_LOSS_WEIGHT: 25.0
    VISION_FUSION_TYPE: "gating"
    VISION_LOSS_WEIGHT: 1.0
    NUM_VISION_EXPERTS: 4
    NUM_LLM_EXPERTS: 2
    NUM_VL_EXPERTS: 4