DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 16
  NUM_WORKERS: 8

INPUT:
  SIZE: (512, 512)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]
  TRANSFORMS: ["normalize"]

MODEL:
  NAME: "pixart"
  CONFIG: "/path/to/transagent/configs/pixart/PixArt_xl2_img512.py"
